#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do. Every\n' "$DIM"
  printf '  value it asks for is typed into Vercel by you, not saved here — so a\n'
  printf '  Ctrl-C costs you the stages you had already done.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}" || true
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}" || true
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# STAGES — the Vercel project for this repo, created once by hand.
# Nothing here is written to .env: every value belongs in Vercel's dashboard,
# and production credentials must not land in a local file.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Grimoria — Vercel production setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Neon — region, and whether main is already dirty"
say "Two facts from Neon before Vercel exists: the region to match, and whether"
say "main already holds tables. A first migration against a non-empty schema fails."
open_url "https://console.neon.tech/"
step "Open the project. The region is under the project name, e.g. 'AWS eu-central-1'."
ask NEON_REGION "Paste the Neon region (e.g. aws-eu-central-1):"
step "Switch the branch selector to 'main', then open Tables."
if confirm "Does main already list tables?"; then
  warn "Drop them, or reset main from an empty branch, before the first deploy."
  warn "Otherwise 'payload migrate' fails on CREATE TABLE and no deploy is produced."
  pause "Press Enter once main is empty."
fi
step "Copy main's POOLED connection string (host contains '-pooler')."
step "Then toggle to the DIRECT one (no '-pooler') and copy that too — stage 5 needs both."
pause "Got both strings?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Vercel — create the project"
say "Import this repository. Leave the framework preset alone; Next.js is detected."
open_url "https://vercel.com/new"
step "Pick the grimoria repository and click Import."
step "Root directory stays './'. Do NOT deploy yet — skip past the env var form."
note "A first deploy without the variables below just fails; the next one fixes it."
pause "Project created?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Vercel — override the build command"
say "The default 'yarn build' runs no migrations. Production must run them first."
step "Settings → Build and Deployment → Build Command → Override."
step "Enter exactly:  yarn build:migrate"
note "That is 'payload migrate && next build'. A failing migration fails the build."
step "While here, confirm Node.js Version is 24.x — package.json pins it too."
pause "Build command overridden?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel — match the function region to Neon"
say "Functions in one region talking to a database in another pay the round trip"
say "on every query. Neon's region, from stage 1, was: ${NEON_REGION}"
step "Settings → Functions → Function Region."
step "Pick the region matching ${NEON_REGION}."
note "This lives in the dashboard, not vercel.json — a committed region would go on"
note "claiming a region the database had left."
pause "Region matched?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vercel — production environment variables"
say "Five variables, Production scope only. Preview and Development are out of scope."
step "Settings → Environment Variables. For each, check Production and uncheck the rest."
say ""
step "DATABASE_URL          → Neon main, POOLED string (host has '-pooler')"
step "DATABASE_URL_UNPOOLED → Neon main, DIRECT string (no '-pooler')"
step "BETTER_AUTH_URL       → the production origin, e.g. https://grimoria.vercel.app"
note "  Written out, so a post-sign-in redirect cannot land on a preview URL."
say ""
say "  And two secrets, each its own value — never the ones in your local .env:"
for key in PAYLOAD_SECRET BETTER_AUTH_SECRET; do
  suggestion=$(openssl rand -hex 32 2>/dev/null || echo "")
  if [[ -n "$suggestion" ]]; then
    step "$key"
    printf '\n      %s%s%s\n\n' "$BOLD" "$suggestion" "$RESET"
  else
    step "$key → generate one: openssl rand -hex 32"
  fi
done
note "BETTER_AUTH_SECRET is not optional: nothing passes Better Auth a secret in code,"
note "so in production it throws at boot rather than falling back."
pause "All five saved, Production only?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Deploy, and prove it works"
say "'It deployed' and 'it works' are different claims. Check both."
open_url "https://vercel.com/dashboard"
step "Deployments → Redeploy the latest, with cache off."
step "In the build log, find the 'payload migrate' output above the Next.js build."
if ! confirm "Did the build succeed with the migration applied?"; then
  warn "Read the migrate output. A non-empty main (stage 1) is the usual cause."
  warn "Re-run this wizard once it is sorted."
  exit 1
fi
step "Open <your-domain>/cms, sign in, and create or edit a record."
step "Back in Neon, on branch main, confirm that row exists in the table."
if confirm "Record written, and visible in Neon main?"; then
  say "Production is live against main."
else
  SKIPPED+=("Confirm the deployed admin reads and writes Neon main")
fi

finish
