import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { postgresAdapter } from '@payloadcms/db-postgres';
import { admin } from 'better-auth/plugins';
import { buildConfig } from 'payload';
import { betterAuthPlugin } from 'payload-auth/better-auth/plugin';

import { sessionCookiesPlugin } from './auth/sessionCookiesPlugin';
import { withInviteExpiry } from './collections/admin-invitations';
import { withProfileFields } from './collections/users';
import { BETTER_AUTH_URL, DATABASE_URL, PAYLOAD_SECRET } from './constants/env';
import { ROUTES } from './constants/routes';
import { SESSION_EXPIRES_IN, SESSION_UPDATE_AGE } from './constants/user';

const dirname = path.dirname(fileURLToPath(import.meta.url));

export default buildConfig({
  // None of our own yet. `users`, `sessions`, `accounts`, `verifications` and
  // `admin-invitations` are generated by the plugin below (ADR-0009).
  collections: [],

  plugins: [
    betterAuthPlugin({
      // The login screen mints the first admin's invite itself, and omits the
      // one field it declares required — see `withInviteExpiry`.
      adminInvitations: {
        collectionOverrides: withInviteExpiry,
      },

      users: {
        roles: ['user', 'moderator'],
        adminRoles: ['admin'],
        defaultRole: 'user',

        // What a User may change about themselves. `role` is absent, which is
        // what stops a User from promoting themselves to admin; `slug` is
        // absent until the profile screen can validate a chosen one (#5).
        allowedFields: ['name', 'theme'],

        collectionOverrides: withProfileFields,
      },

      betterAuthOptions: {
        // Better Auth reads this from the environment on its own, but the
        // admin's login screen is handed the value from here, so it is passed
        // explicitly. Unset, both fall back to the request's own origin.
        baseURL: BETTER_AUTH_URL,

        emailAndPassword: { enabled: true },

        // In memory means one counter per serverless instance — ten instances,
        // ten times the limit. Postgres is the only store all of them share.
        rateLimit: { storage: 'database' },

        // A session slides: any Better Auth request older than `updateAge`
        // pushes `expiresIn` out again, so a User who shows up inside two weeks
        // is never signed out. This is what a refresh token buys elsewhere.
        session: {
          expiresIn: SESSION_EXPIRES_IN,
          updateAge: SESSION_UPDATE_AGE,
        },

        plugins: [admin(), sessionCookiesPlugin()],
      },
    }),
  ],

  // Every read and write goes through the Local API in process
  // (`docs/features/data-access.md`), so the generated GraphQL endpoint had no
  // caller and stayed an unauthenticated public surface nobody exercised. #33.
  graphQL: {
    disable: true,
  },

  // Names what it is, and also places `importMap.js` — hence the folder name
  // under `(payload)`. ADR-0005.
  routes: {
    admin: ROUTES.ADMIN,
  },

  admin: {
    components: {
      // Payload's nav has no way out of `/cms` on its own.
      beforeNavLinks: ['/admin/BackToSite#BackToSite'],
    },

    importMap: {
      baseDir: path.resolve(dirname),
    },
  },

  // A browser-minted UUID is the primary key an optimistic create addresses a
  // drawn-but-unsent row with (ADR-0010). Without `allowIDOnCreate` the adapter
  // discards it silently and the optimistic key is orphaned.
  db: postgresAdapter({
    pool: { connectionString: DATABASE_URL },
    idType: 'uuid',
    allowIDOnCreate: true,
  }),

  secret: PAYLOAD_SECRET,

  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
});
