import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { postgresAdapter } from '@payloadcms/db-postgres';
import { admin } from 'better-auth/plugins';
import { buildConfig } from 'payload';
import { betterAuthPlugin } from 'payload-auth/better-auth/plugin';

import { withInviteExpiry } from './collections/admin-invitations';
import { withProfileFields } from './collections/users';
import { ROUTES } from './constants/routes';
import { SESSION_EXPIRES_IN, SESSION_UPDATE_AGE } from './constants/user';

const dirname = path.dirname(fileURLToPath(import.meta.url));

// Neon's pooled endpoint runs PgBouncer in transaction mode, where the `SET`
// statements schema work relies on do not survive between transactions. Schema
// work is exactly the two cases the adapter itself checks for: dev push
// (`NODE_ENV !== 'production'`) and `payload migrate` (`PAYLOAD_MIGRATING`).
// Everything else is serverless request traffic, which is what pooling is for.
const isSchemaOperation =
  process.env.NODE_ENV !== 'production' || process.env.PAYLOAD_MIGRATING === 'true';

// Neon hands out `sslmode=require`, which `pg` treats as `verify-full` today
// and warns about on every boot, because `pg@9` will downgrade it to libpq's
// weaker meaning. Asking for `verify-full` outright keeps the behavior we
// already have — Neon's certificates are publicly trusted — and drops the
// warning, without every environment having to edit its own connection string.
const connectionString = (
  isSchemaOperation
    ? process.env.DATABASE_URL_UNPOOLED || process.env.DATABASE_URL || ''
    : process.env.DATABASE_URL || ''
).replace('sslmode=require', 'sslmode=verify-full');

export default buildConfig({
  // None of our own yet. `users`, `sessions`, `accounts`, `verifications` and
  // `admin-invitations` are generated by the plugin below (ADR-0009).
  collections: [],

  plugins: [
    betterAuthPlugin({
      // The login screen mints the first admin's invite itself, and omits the
      // one field it declares required — see `withInviteExpiry`.
      adminInvitations: {
        collectionOverrides: withInviteExpiry,
      },

      users: {
        roles: ['user', 'moderator'],
        adminRoles: ['admin'],
        defaultRole: 'user',

        // What a User may change about themselves. `role` is absent, which is
        // what stops a User from promoting themselves to admin; `slug` is
        // absent until the profile screen can validate a chosen one (#5).
        allowedFields: ['name', 'theme'],

        collectionOverrides: withProfileFields,
      },

      betterAuthOptions: {
        // Better Auth reads this from the environment on its own, but the
        // admin's login screen is handed the value from here, so it is passed
        // explicitly. Unset, both fall back to the request's own origin.
        baseURL: process.env.BETTER_AUTH_URL,

        emailAndPassword: { enabled: true },

        // Better Auth counts requests in memory by default, which on serverless
        // means one counter per instance — ten instances, ten times the limit.
        // Postgres is the only store every instance shares; `payload-auth` turns
        // this into the generated `rateLimit` collection.
        rateLimit: { storage: 'database' },

        // A session slides: any Better Auth request older than `updateAge`
        // pushes `expiresIn` out again, so a User who shows up inside two weeks
        // is never signed out. This is what a refresh token buys elsewhere.
        session: {
          expiresIn: SESSION_EXPIRES_IN,
          updateAge: SESSION_UPDATE_AGE,
        },

        plugins: [admin()],
      },
    }),
  ],

  // Names what it is, and also places `importMap.js` — hence the folder name
  // under `(payload)`. ADR-0005.
  routes: {
    admin: ROUTES.ADMIN,
  },

  admin: {
    components: {
      // Payload's nav has no way out of `/cms` on its own.
      beforeNavLinks: ['/admin/BackToSite#BackToSite'],
    },

    importMap: {
      baseDir: path.resolve(dirname),
    },
  },

  // A UUID the browser mints is the row's primary key from the first millisecond,
  // which is what an optimistic create needs to address a row it has drawn but not
  // yet sent (ADR-0010). `allowIDOnCreate` is the half that is easy to lose: false,
  // the adapter silently discards the supplied id and allocates its own, and the
  // optimistic key is orphaned without anything throwing.
  db: postgresAdapter({
    pool: { connectionString },
    idType: 'uuid',
    allowIDOnCreate: true,
  }),

  secret: process.env.PAYLOAD_SECRET || '',

  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
});
